[[npc]]
id = "npc.goblin_cook_boss"
inherit = "npc.goblin_armed_melee_1"
name = "The Goblin COOK"
size = 2
combatLevel = 45
widthScale = 300
heightScale = 300
models = [24458, 24486, 24437, 24475, 24442, 24450, 24491, 199, 24498]
originalColours = [4515, 6040, 6323, 6331, 6348, 6356, 6955, 7073, 7075, 8084, 8596, 9112, 10308, 43038, 43047, 43055, 43072, 43080, 664, 912]
modifiedColours = [97, 86, 113, 121, 127, 127, 105, 95, 97, 82, 82, 86, 127, 85, 94, 102, 119, 127, 7576, 7568]
hitpoints = 50000
attack = 40
strength = 40
defence = 30
respawnRate = 25
wanderRange = 3
huntRange = 6
examine = "He's been tasting the stew a bit too often."
[npc.params]
"param.attack_sound"=469
"param.defend_sound"=472
"param.death_sound"=471
"param.attack_anim"="seq.slice_surface_goblin_squat_unarmed_attack"
"param.defend_anim"="seq.slice_surface_goblin_defend"
"param.death_anim"="seq.slice_surface_goblin_death"
"param.npc_attack_type"="category.attacktype_slash"
"param.boss_hp_bar_mode"=1

[[graphic]]
id = "spotanim.goblin_cook_knife_travel"
inherit = "spotanim.rune_tknife_travel"
resizeX = 384
resizeY = 384
