[gamevals.interface]
boss_atlas = 1106

[gamevals.npc]
boss_guide = 65510

[gamevals.clientscript]
boss_atlas_init = 45600
boss_atlas_tabs = 45603
boss_atlas_row = 45606
boss_atlas_row_hover = 45609
boss_atlas_list_done = 45612
boss_atlas_list_clear = 45615
boss_atlas_buttons = 45618
boss_atlas_drops_clear = 45621
boss_atlas_drop = 45624
boss_atlas_search_op = 45627
boss_atlas_search_key = 45630
boss_atlas_search_tick = 45633
boss_atlas_search_stop = 45639
boss_atlas_details_icons = 45645

[gamevals.varp]
boss_atlas_pb_zulrah = 64000
boss_atlas_pb_vorkath = 64001
boss_atlas_pb_cerberus = 64002
boss_atlas_pb_sire = 64003
boss_atlas_pb_hydra = 64004
boss_atlas_pb_kraken = 64005
boss_atlas_pb_thermy = 64006
boss_atlas_pb_corp = 64007
boss_atlas_pb_dks = 64008
boss_atlas_pb_mole = 64009
boss_atlas_pb_kq = 64010
boss_atlas_pb_kbd = 64011
boss_atlas_pb_sarachnis = 64012
boss_atlas_pb_scurrius = 64013
boss_atlas_pb_barrows = 64014
boss_atlas_pb_graardor = 64015
boss_atlas_pb_kreearra = 64016
boss_atlas_pb_zilyana = 64017
boss_atlas_pb_kril = 64018
boss_atlas_pb_nex = 64019
boss_atlas_pb_nightmare = 64020
boss_atlas_pb_muspah = 64021
boss_atlas_pb_huey = 64022
boss_atlas_pb_yama = 64023
boss_atlas_pb_titans = 64024
boss_atlas_pb_amoxliatl = 64025
boss_atlas_pb_vardorvis = 64026
boss_atlas_pb_leviathan = 64027
boss_atlas_pb_whisperer = 64028
boss_atlas_pb_duke = 64029
boss_atlas_pb_callisto = 64030
boss_atlas_pb_venenatis = 64031
boss_atlas_pb_vetion = 64032
boss_atlas_pb_chaosele = 64033
boss_atlas_pb_scorpia = 64034
boss_atlas_pb_cox = 64035
boss_atlas_pb_tob = 64036
boss_atlas_pb_toa = 64037
boss_atlas_loot_zulrah = 64040
boss_atlas_loot_vorkath = 64041
boss_atlas_loot_cerberus = 64042
boss_atlas_loot_sire = 64043
boss_atlas_loot_hydra = 64044
boss_atlas_loot_kraken = 64045
boss_atlas_loot_thermy = 64046
boss_atlas_loot_corp = 64047
boss_atlas_loot_dks = 64048
boss_atlas_loot_mole = 64049
boss_atlas_loot_kq = 64050
boss_atlas_loot_kbd = 64051
boss_atlas_loot_sarachnis = 64052
boss_atlas_loot_scurrius = 64053
boss_atlas_loot_barrows = 64054
boss_atlas_loot_graardor = 64055
boss_atlas_loot_kreearra = 64056
boss_atlas_loot_zilyana = 64057
boss_atlas_loot_kril = 64058
boss_atlas_loot_nex = 64059
boss_atlas_loot_nightmare = 64060
boss_atlas_loot_muspah = 64061
boss_atlas_loot_huey = 64062
boss_atlas_loot_yama = 64063
boss_atlas_loot_titans = 64064
boss_atlas_loot_amoxliatl = 64065
boss_atlas_loot_vardorvis = 64066
boss_atlas_loot_leviathan = 64067
boss_atlas_loot_whisperer = 64068
boss_atlas_loot_duke = 64069
boss_atlas_loot_callisto = 64070
boss_atlas_loot_venenatis = 64071
boss_atlas_loot_vetion = 64072
boss_atlas_loot_chaosele = 64073
boss_atlas_loot_scorpia = 64074
boss_atlas_loot_cox = 64075
boss_atlas_loot_tob = 64076
boss_atlas_loot_toa = 64077
boss_atlas_favs = 64080
boss_atlas_misc = 64081
boss_atlas_ui = 64082
boss_atlas_cooldown = 64083

[gamevals.varbit]
boss_atlas_fav0 = 64000
boss_atlas_fav1 = 64001
boss_atlas_fav2 = 64002
boss_atlas_fav3 = 64003
boss_atlas_fav4 = 64004
boss_atlas_last = 64005
boss_atlas_tab = 64006
boss_atlas_selected = 64007
boss_atlas_drops_view = 64008
