[[npc]]
id = "npc.broodmother"
inherit = "npc.poisonspider"
name = "Broodmother"
size = 4
combatLevel = 172
models = ["models.broodmother"]
standAnim = "seq.broodmother_stand"
walkAnim = "seq.broodmother_walk"
rotateLeftAnim = "seq.broodmother_walk"
rotateRightAnim = "seq.broodmother_walk"
rotateBackAnim = "seq.broodmother_walk"
walkLeftAnim = "seq.broodmother_walk"
walkRightAnim = "seq.broodmother_walk"
runSequence = "seq.broodmother_walk"
runBackSequence = "seq.broodmother_walk"
runLeftSequence = "seq.broodmother_walk"
runRightSequence = "seq.broodmother_walk"
widthScale = 128
heightScale = 128
hitpoints = 450
attack = 150
strength = 140
defence = 120
ranged = 130
magic = 60
respawnRate = 50
wanderRange = 3
huntRange = 8
examine = "A bloated tick queen, swollen with venom."
[npc.params]
"param.attack_anim"="seq.broodmother_attack"
"param.defend_anim"="seq.broodmother_defend"
"param.death_anim"="seq.broodmother_death"
"param.npc_attack_type"="category.attacktype_stab"
"param.boss_hp_bar_mode"=1
