[[item]]
id = "obj.poison_blades"
inherit = "obj.dual_macuahuitl"
name = "Poison Blades"
inventoryModel = "models.poison_blades"
maleModel0 = "models.poison_blades_worn"
femaleModel0 = "models.poison_blades_worn"
examine = "Twin blades slick with a venom that never seems to dry."
weaponCategory = "Spiked"
[item.params]
"param.attack_anim_stance1" = "seq.human_dragon_claws_spec"
"param.attack_anim_stance2" = "seq.human_dragon_claws_spec"
"param.attack_anim_stance3" = "seq.human_dragon_claws_spec"
"param.attack_anim_stance4" = "seq.human_dragon_claws_spec"
"param.attack_sound_stance1" = 7930
"param.attack_sound_stance2" = 7930
"param.attack_sound_stance3" = 7930
"param.attack_sound_stance4" = 7930
"param.equipment_sound" = 2233
"param.defend_anim" = "seq.human_unarmedblock"

[[graphic]]
id = "spotanim.poison_blades_xslash"
inherit = "spotanim.sp_attack_dragon_scimitar_trail_spotanim"
originalColours = [960]
modifiedColours = [22480]
