[[enum]]
id = "enum.stat_names"
keyType = "INT"
valueType = "STRING"
default = "this skill"

[enum.values]
1 = "Attack"
2 = "Strength"
3 = "Ranged"
4 = "Magic"
5 = "Defence"
6 = "Hitpoints"
7 = "Prayer"
8 = "Agility"
9 = "Herblore"
10 = "Thieving"
11 = "Crafting"
12 = "Runecraft"
13 = "Mining"
14 = "Smithing"
15 = "Fishing"
16 = "Cooking"
17 = "Firemaking"
18 = "Woodcutting"
19 = "Fletching"
20 = "Slayer"
21 = "Farming"
22 = "Construction"
23 = "Hunter"
24 = "Poison Mastery"
