[gamevals.npc]
home_ironman_shopkeeper = 65530
home_general_shopkeeper = 65531

[gamevals.inv]
home_general_supplies = 1104
home_general_gear = 1105
home_ironman_supplies = 1106
home_ironman_gear = 1107
